// <auto-generated />
using System;
using Eymta.Repository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eymta.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eymta.core.Notification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsRead").HasColumnType("boolean");
                b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<int?>("TaskId").HasColumnType("integer");
                b.Property<string>("Type").IsRequired().HasColumnType("text");
                b.Property<int>("UserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("TaskId");
                b.HasIndex("UserId");
                b.ToTable("Notifications");
            });

            modelBuilder.Entity("Eymta.core.TaskAttachment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("ContentType").HasColumnType("text");
                b.Property<string>("FileName").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                b.Property<string>("FilePath").IsRequired().HasColumnType("text");
                b.Property<long>("FileSizeBytes").HasColumnType("bigint");
                b.Property<int>("TaskId").HasColumnType("integer");
                b.Property<DateTime>("UploadedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("UploadedByUserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("TaskId");
                b.HasIndex("UploadedByUserId");
                b.ToTable("TaskAttachments");
            });

            modelBuilder.Entity("Eymta.core.TaskComment", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Comment").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("TaskId").HasColumnType("integer");
                b.Property<int>("UserId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("TaskId");
                b.HasIndex("UserId");
                b.ToTable("TaskComments");
            });

            modelBuilder.Entity("Eymta.core.TaskItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int?>("AssignedToTeamId").HasColumnType("integer");
                b.Property<int?>("AssignedToUserId").HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("CreatedById").HasColumnType("integer");
                b.Property<string>("Description").HasColumnType("text");
                b.Property<DateTime>("DueDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Priority").IsRequired().HasColumnType("text");
                b.Property<DateTime>("StartDate").HasColumnType("timestamp with time zone");
                b.Property<string>("Status").IsRequired().HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.HasKey("Id");
                b.HasIndex("AssignedToTeamId");
                b.HasIndex("AssignedToUserId");
                b.HasIndex("CreatedById");
                b.ToTable("Tasks");
            });

            modelBuilder.Entity("Eymta.core.Team", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Color").HasMaxLength(10).HasColumnType("character varying(10)");
                b.Property<int?>("LeaderId").HasColumnType("integer");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.HasKey("Id");
                b.HasIndex("LeaderId");
                b.ToTable("Teams");
            });

            modelBuilder.Entity("Eymta.core.TeamMessage", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("Message").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.Property<int>("SenderId").HasColumnType("integer");
                b.Property<DateTime>("SentAt").HasColumnType("timestamp with time zone");
                b.Property<int>("TeamId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("SenderId");
                b.HasIndex("TeamId");
                b.ToTable("TeamMessages");
            });

            modelBuilder.Entity("Eymta.core.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<DateTime?>("LastSeenAt").HasColumnType("timestamp with time zone");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Role").IsRequired().HasColumnType("text");
                b.Property<int?>("TeamId").HasColumnType("integer");
                b.Property<string>("Username").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("TeamId");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}
